<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Syncfusion.SfChart.WPF" Version="*" />
    <PackageReference Include="Syncfusion.Shared.WPF" Version="*" />
    <PackageReference Include="syncfusion.ui.wpf.net" Version="*" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\energyConsumption.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\renewableEnergy.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
